# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='secrets_liked', to='first_app.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
