# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170424_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='likes',
        ),
        migrations.AddField(
            model_name='secret',
            name='list_of_users_liked',
            field=models.ManyToManyField(related_name='list_of_secrets_liked', to='first_app.User'),
        ),
    ]
